### ISSUE TITLE
CAN'T RUN IN WIN10

### ISSUE THREAD

**Issue by AstoncPou** [HelloRicky123/Siamese-RPN#12]
when i run the demo_siamesefc.py in win10 ,it report the error:
>D:\code\SiamFC-PyTorch-master\SiamFC-PyTorch>python bin/demo_siamfc.py --video-dir D:/code/SiamFC-PyTorch-master/SiamFC-PyTorch/data/David  --gpu-id 0 --model-path D:/code/SiamFC-PyTorch-master/SiamFC-PyTorch/models
Traceback (most recent call last):
  File "bin/demo_siamfc.py", line 57, in <module>
    Fire(main)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "bin/demo_siamfc.py", line 27, in main
    tracker = SiamFCTracker(model_path, gpu_id)
  File "D:\code\SiamFC-PyTorch-master\SiamFC-PyTorch\siamfc\tracker.py", line 23, in __init__
    self.model.load_state_dict(torch.load(model_path))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\serialization.py", line 365, in load
    f = open(f, 'rb')
PermissionError: [Errno 13] Permission denied: 'D:/code/SiamFC-PyTorch-master/SiamFC-PyTorch/models'
>>>>>>
even i have restart the cmd window and Run as an administrator,when i run the demo_simesefc in ubuntu  because i haven't install GPU-driver in ubuntu ,so please give me an hand as soon as you seen it.thanks

**Comment by HelloRicky123** [comment]
Starting the cmd with super account will help.
