### ISSUE TITLE
I run your program and got only 0.1%AUC on OTB100

### ISSUE THREAD

**Issue by Yvonneie** [HelloRicky123/Siamese-RPN#48]
Thanks for your work at first. I download your code and just change "data_path" in file "test_OTB100" to my folder of OTB100 sequences , and use the model "siamrpn_38"that you provided, but when I run "test_OTB100.py" ,I got only 0.1% AUC on that. and I don't know why. Is there anything I forgot, or anything I did wrong ?

**Comment by Clannad000000** [comment]
Have you solved this problem?When I run the basketabll sequence,I find the results have many minus...

**Comment by lgdhang** [comment]
I have this problem either.

**Comment by renlicheng** [comment]
When I run "test_OTB100"，I had this problem In the test frame： Can you help me！！

/home/rlc/anaconda3/envs/H_R-Siamese-RPN/bin/python /home/rlc/H_R-Siamese-RPN/bin/test_OTB.py -ms /home/rlc/H_R-Siamese-RPN/imagenet_pretrain/siamrpn_38.pth -v tb100
  0%|          | 0/3 [00:00<?, ?it/s]
  0%|          | 0/98 [00:00<?, ?it/s]

  0%|          | 0/725 [00:00<?, ?it/s]

  0%|          | 1/725 [00:00<02:01,  5.96it/s]/home/rlc/H_R-Siamese-RPN/lib/utils.py:165: RuntimeWarning: overflow encountered in multiply
  box_w = anchor_w * np.exp(offset_w)
/home/rlc/H_R-Siamese-RPN/lib/utils.py:166: RuntimeWarning: overflow encountered in multiply
  box_h = anchor_h * np.exp(offset_h)
/home/rlc/H_R-Siamese-RPN/net/tracker.py:106: RuntimeWarning: overflow encountered in multiply
  sz2 = (w + pad) * (h + pad)
/home/rlc/H_R-Siamese-RPN/net/tracker.py:102: RuntimeWarning: divide by zero encountered in true_divide
  return np.maximum(r, 1. / r)
/home/rlc/H_R-Siamese-RPN/net/tracker.py:115: RuntimeWarning: divide by zero encountered in true_divide
  r_c = change((self.target_sz[0] / self.target_sz[1]) / (box_pred[:, 2] / box_pred[:, 3]))  # ratio penalty
/home/rlc/H_R-Siamese-RPN/net/tracker.py:115: RuntimeWarning: invalid value encountered in true_divide
  r_c = change((self.target_sz[0] / self.target_sz[1]) / (box_pred[:, 2] / box_pred[:, 3]))  # ratio penalty
  0%|          | 1/725 [00:00<02:09,  5.58it/s]
  0%|          | 0/98 [00:02<?, ?it/s]
  0%|          | 0/3 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/rlc/H_R-Siamese-RPN/bin/test_OTB.py", line 149, in <module>
    result = run_SiamRPN(video_path, model_path, boxes[0])
  File "/home/rlc/H_R-Siamese-RPN/net/run_SiamRPN.py", line 44, in run_SiamRPN
    bbox, score = tracker.update(frame)  # x,y,w,h
  File "/home/rlc/H_R-Siamese-RPN/net/tracker.py", line 86, in update
    config.context_amount, self.img_mean)
  File "/home/rlc/H_R-Siamese-RPN/lib/utils.py", line 131, in get_instance_image
    instance_img, scale_x = crop_and_pad(img, cx, cy, size_x, s_x, img_mean)
  File "/home/rlc/H_R-Siamese-RPN/lib/utils.py", line 86, in crop_and_pad
    xmin = int(round_up(xmin + left))
ValueError: cannot convert float NaN to integer

**Comment by sing-hui** [comment]
I have the same  problem, do you have solved it ?

**Comment by chengxianda54321** [comment]
my model get 0.21 auc, f**k
