### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by Manguotree** [HelloRicky123/Siamese-RPN#53]
Traceback (most recent call last):
  File "bin/train_siamrpn.py", line 14, in <module>
    Fire(train)
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/yangli/zqw/zhu/Siamese-RPN-master/net/train.py", line 170, in train
    for i, data in enumerate(tqdm(trainloader)):
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yangli/anaconda3/envs/mm/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yangli/zqw/zhu/Siamese-RPN-master/net/dataset.py", line 132, in __getitem__
    exemplar_img = self.imread(exemplar_name)
  File "/home/yangli/zqw/zhu/Siamese-RPN-master/net/dataset.py", line 57, in imread
    img_buffer = np.frombuffer(img_buffer, np.uint8)
TypeError: a bytes-like object is required, not 'NoneType'

  0%|                                                                                                        | 0/1403 [00:13<?, ?it/s]

please help me!!  thanks

**Comment by cifar10** [comment]
perhaps，When you generated the lmdb file，you changed the name of the storage VID+Yotu_bb folder, resulting in the original path of the image not being read from the lmdb file.

**Comment by Manguotree** [comment]
thanks!!  I found the problem, Maybe my video name  in VID+Yotu_bb  has been garbled after moving the number set

**Comment by Manguotree** [comment]
thanks!! I found the problem, Maybe my video name in VID+Yotu_bb has been garbled after moving the number set

**Comment by Manguotree** [comment]
> perhaps，When you generated the lmdb file，you changed the name of the storage VID+Yotu_bb folder, resulting in the original path of the image not being read from the lmdb file.

thanks!! I found the problem, Maybe my video name in VID+Yotu_bb has been garbled after moving the number set
